#!/bin/bash

g++ -std=c++11  main.cpp ${PWD}/src/com.cpp  ${PWD}/src/controller.cpp /home/pi/coding/Helix/src/mpu9150.cpp /home/pi/coding/Helix/src/pwm.cpp /home/pi/coding/Helix/src/motors.cpp /home/pi/coding/Helix/src/i2c.cpp  -o helix
